# -*- coding: utf-8 -*-
"""Generate db/init.sql from events.manual.json + seats.manual.csv"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
OUT = REPO / "db" / "init.sql"


def esc(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def main():
    events = json.loads((ROOT / "events.manual.json").read_text(encoding="utf-8"))
    seats = []
    with (ROOT / "seats.manual.csv").open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            seats.append(r)

    lines = []
    a = lines.append

    a("-- =============================================================================")
    a("-- War Tiket Konser - Klpk1")
    a("-- Schema + seed dari DATA_WAR_TIKET_KONSER.xlsx")
    a("-- Events: TREASURE, LYKN, BLACKPINK, NCT DREAM, EXO, ATEEZ, BUS")
    a(f"-- Total seats seed: {len(seats)}")
    a("-- Generated by: python data/generate_init_sql.py")
    a("-- JANGAN edit manual seed Coldplay lama. Ubah Excel -> import -> regenerate.")
    a("-- =============================================================================")
    a("")
    a('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    a("")
    a("-- ----- venues -----")
    a("CREATE TABLE IF NOT EXISTS venues (")
    a("  venue_id    VARCHAR(20) PRIMARY KEY,")
    a("  venue_code  VARCHAR(40),")
    a("  venue_name  VARCHAR(200) NOT NULL,")
    a("  city        VARCHAR(80),")
    a("  address     TEXT,")
    a("  capacity    INT,")
    a("  status      VARCHAR(20) DEFAULT 'ACTIVE'")
    a(");")
    a("")
    a("-- ----- events -----")
    a("CREATE TABLE IF NOT EXISTS events (")
    a("  event_id         SERIAL PRIMARY KEY,")
    a("  event_code       VARCHAR(40),")
    a("  title            VARCHAR(200) NOT NULL,")
    a("  artist           VARCHAR(150) NOT NULL,")
    a("  venue            VARCHAR(200) NOT NULL,")
    a("  venue_id         VARCHAR(20),")
    a("  starts_at        TIMESTAMPTZ NOT NULL,")
    a("  ends_at          TIMESTAMPTZ,")
    a("  sales_opens_at   TIMESTAMPTZ NOT NULL,")
    a("  sales_closes_at  TIMESTAMPTZ,")
    a("  quota_total      INT NOT NULL CHECK (quota_total > 0),")
    a("  price_idr        BIGINT NOT NULL CHECK (price_idr >= 0),")
    a("  status           VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',")
    a("  city             VARCHAR(80),")
    a("  country          VARCHAR(80),")
    a("  description      TEXT,")
    a("  gate_open        VARCHAR(40),")
    a("  age_rating       VARCHAR(80),")
    a("  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()")
    a(");")
    a("")
    a("-- ----- seat_categories -----")
    a("CREATE TABLE IF NOT EXISTS seat_categories (")
    a("  event_id   INT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,")
    a("  code       VARCHAR(20) NOT NULL,")
    a("  name       VARCHAR(120) NOT NULL,")
    a("  price_idr  BIGINT NOT NULL,")
    a("  quota      INT NOT NULL,")
    a("  color_hex  VARCHAR(7),")
    a("  PRIMARY KEY (event_id, code)")
    a(");")
    a("")
    a("-- ----- seats (denah) -----")
    a("CREATE TABLE IF NOT EXISTS seats (")
    a("  event_id        INT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,")
    a("  seat_code       VARCHAR(20) NOT NULL,")
    a("  category        VARCHAR(40) NOT NULL DEFAULT 'REG',")
    a("  category_name   VARCHAR(120),")
    a("  row_label       VARCHAR(10) NOT NULL,")
    a("  seat_number     INT NOT NULL,")
    a("  section         VARCHAR(80),")
    a("  price_idr       BIGINT,")
    a("  color_hex       VARCHAR(7),")
    a("  pos_x           INT,")
    a("  pos_y           INT,")
    a("  PRIMARY KEY (event_id, seat_code)")
    a(");")
    a("CREATE INDEX IF NOT EXISTS idx_seats_event_cat ON seats(event_id, category);")
    a("")
    a("-- ----- orders -----")
    a("CREATE TABLE IF NOT EXISTS orders (")
    a("  order_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    a("  event_id      INT NOT NULL REFERENCES events(event_id),")
    a("  qty           INT NOT NULL CHECK (qty > 0 AND qty <= 4),")
    a("  amount_idr    BIGINT NOT NULL,")
    a("  status        VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',")
    a("  client_ip     VARCHAR(64),")
    a("  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()")
    a(");")
    a("CREATE INDEX IF NOT EXISTS idx_orders_event ON orders(event_id);")
    a("CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);")
    a("")
    a("CREATE TABLE IF NOT EXISTS order_events_audit (")
    a("  audit_id      BIGSERIAL PRIMARY KEY,")
    a("  order_id      UUID,")
    a("  event_id      INT NOT NULL,")
    a("  action        VARCHAR(40) NOT NULL,")
    a("  detail        JSONB,")
    a("  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()")
    a(");")
    a("CREATE INDEX IF NOT EXISTS idx_audit_event ON order_events_audit(event_id);")
    a("")

    # venues unique
    a("-- ----- SEED venues -----")
    seen_v = set()
    for e in events:
        vid = e.get("venue_id")
        if not vid or vid in seen_v:
            continue
        seen_v.add(vid)
        a(
            "INSERT INTO venues (venue_id, venue_code, venue_name, city, address, capacity, status) VALUES ("
            f"{esc(vid)}, {esc(e.get('venue_code'))}, {esc(e.get('venue'))}, "
            f"{esc(e.get('city'))}, NULL, {int(e.get('quota_total') or 0)}, 'ACTIVE'"
            ") ON CONFLICT (venue_id) DO UPDATE SET "
            "venue_name = EXCLUDED.venue_name, city = EXCLUDED.city;"
        )
    a("")

    a("-- ----- SEED events (dataset Excel) -----")
    for e in events:
        a(
            "INSERT INTO events ("
            "event_id, event_code, title, artist, venue, venue_id, "
            "starts_at, ends_at, sales_opens_at, sales_closes_at, "
            "quota_total, price_idr, status, city, country, description, gate_open, age_rating"
            ") VALUES ("
            f"{int(e['event_id'])}, "
            f"{esc(e.get('event_code'))}, "
            f"{esc(e.get('title'))}, "
            f"{esc(e.get('artist'))}, "
            f"{esc(e.get('venue'))}, "
            f"{esc(e.get('venue_id'))}, "
            f"{esc(e.get('starts_at'))}::timestamptz, "
            f"{esc(e.get('ends_at'))}::timestamptz, "
            f"{esc(e.get('sales_opens_at'))}::timestamptz, "
            f"{esc(e.get('sales_closes_at'))}::timestamptz, "
            f"{int(e['quota_total'])}, "
            f"{int(e['price_idr'])}, "
            f"{esc(e.get('status') or 'PUBLISHED')}, "
            f"{esc(e.get('city'))}, "
            f"{esc(e.get('country'))}, "
            f"{esc(e.get('description'))}, "
            f"{esc(e.get('gate_open'))}, "
            f"{esc(e.get('age_rating'))}"
            ") ON CONFLICT (event_id) DO UPDATE SET "
            "event_code = EXCLUDED.event_code, "
            "title = EXCLUDED.title, "
            "artist = EXCLUDED.artist, "
            "venue = EXCLUDED.venue, "
            "venue_id = EXCLUDED.venue_id, "
            "starts_at = EXCLUDED.starts_at, "
            "ends_at = EXCLUDED.ends_at, "
            "sales_opens_at = EXCLUDED.sales_opens_at, "
            "sales_closes_at = EXCLUDED.sales_closes_at, "
            "quota_total = EXCLUDED.quota_total, "
            "price_idr = EXCLUDED.price_idr, "
            "status = EXCLUDED.status, "
            "city = EXCLUDED.city, "
            "country = EXCLUDED.country, "
            "description = EXCLUDED.description, "
            "gate_open = EXCLUDED.gate_open, "
            "age_rating = EXCLUDED.age_rating;"
        )
    a("")
    a(
        "SELECT setval(pg_get_serial_sequence('events', 'event_id'), "
        "GREATEST((SELECT MAX(event_id) FROM events), 1));"
    )
    a("")

    a("-- ----- SEED seat_categories -----")
    for e in events:
        for c in e.get("categories") or []:
            a(
                "INSERT INTO seat_categories (event_id, code, name, price_idr, quota, color_hex) VALUES ("
                f"{int(e['event_id'])}, {esc(c.get('code'))}, {esc(c.get('name'))}, "
                f"{int(c.get('price_idr') or 0)}, {int(c.get('quota') or 0)}, {esc(c.get('color'))}"
                ") ON CONFLICT (event_id, code) DO UPDATE SET "
                "name = EXCLUDED.name, price_idr = EXCLUDED.price_idr, "
                "quota = EXCLUDED.quota, color_hex = EXCLUDED.color_hex;"
            )
    a("")

    a("-- ----- SEED seats (full denah) -----")
    a("-- Hapus denah lama lalu insert dataset baru (idempotent re-init)")
    a("TRUNCATE seats;")
    # batch inserts
    batch = []
    batch_size = 80

    def flush():
        nonlocal batch
        if not batch:
            return
        a(
            "INSERT INTO seats ("
            "event_id, seat_code, category, category_name, row_label, seat_number, "
            "section, price_idr, color_hex, pos_x, pos_y"
            ") VALUES"
        )
        a(",\n".join(batch) + ";")
        batch = []

    for s in seats:
        batch.append(
            "("
            f"{int(s['event_id'])}, "
            f"{esc(s.get('seat_code'))}, "
            f"{esc(s.get('category'))}, "
            f"{esc(s.get('category_name'))}, "
            f"{esc(s.get('row_label'))}, "
            f"{int(float(s.get('seat_number') or 0))}, "
            f"{esc(s.get('section'))}, "
            f"{int(float(s.get('price_idr') or 0))}, "
            f"{esc(s.get('color_hex') or None)}, "
            f"{int(float(s['pos_x'])) if str(s.get('pos_x') or '').strip() not in ('', 'None') else 'NULL'}, "
            f"{int(float(s['pos_y'])) if str(s.get('pos_y') or '').strip() not in ('', 'None') else 'NULL'}"
            ")"
        )
        if len(batch) >= batch_size:
            flush()
    flush()
    a("")
    a(f"-- done: {len(events)} events, {len(seats)} seats")
    a("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("WROTE", OUT, "bytes", OUT.stat().st_size)
    print("events", len(events), "seats", len(seats))


if __name__ == "__main__":
    main()
